server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /happiness { rewrite ^ /index.html?venue=happiness break; }
    location /neuro     { rewrite ^ /index.html?venue=neuro break; }
    location /injoy     { rewrite ^ /index.html?venue=injoy break; }
    location /canteen   { rewrite ^ /index.html?venue=canteen break; }
    location / { try_files $uri $uri/ /index.html; }
}
